### ISSUE TITLE
staging

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/siacoin.com#13]
We should have a staging branch, and a staging domain sitestaging.siacoin.com'.

All changes should be pull requested into the staging branch, that way we can view the website before merging them into master and make sure everything appears on the website the same way that it appeared on our computers.

We're eventually going to want staging for the block explorer as well

**Comment by lukechampine** [comment]
why not just pull the branch and view it locally?

**Comment by DavidVorick** [comment]
you need nginx to view the site,

additionally, the website looked different on ming's computer than it did after I merged his PR. We aren't sure what was causing the disparity but there was clearly a difference.

**Comment by Mingling94** [comment]
Staging branch has been introduced
