### ISSUE TITLE
Server Workings 

### ISSUE THREAD

**Issue by triazo** [NebulousLabs/siacoin.com#2]
Just wanted to document how the server is currently set up. The web root is running out of /srv/www/siacoin.com/. siacoin.com.new and siacoin.com.old are currently not used. It is synced to the this via a github webhook. The webhook listener is a python server running in a tmux session. This same listener also is listening for updates to the Sia-Block-Explorer repo.

**Comment by DavidVorick** [comment]
This should go in a doc folder.

**Comment by triazo** [comment]
Problem is that anything in the repo goes to the web root, which is best to keep clean.

Perhaps make a site/ folder in the root of the repo, and make this the web root? This will also prevent the .git directory from being traversed.

**Comment by DavidVorick** [comment]
that sounds like a much better approach. I think the folder is typically called public_html

**Comment by DavidVorick** [comment]
Can you make a readme with the info from the OP?
