### ISSUE TITLE
Force pull githook

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/siacoin.com#3]
If you amend a commit on master, the githook will break (git diff output will appear on the website). Preferably, it would just pull the change and overwrite the local version. This can be accomplished with `git fetch origin master && git reset --hard origin/master`.

**Comment by triazo** [comment]
Changed to those commands, at least for the siacoin.com repo. Once this is shown to work I'll update it on the other synced repos.

**Comment by DavidVorick** [comment]
seems to not work

**Comment by triazo** [comment]
Is there a new firewall? I can't seem to access the webhook handler from my laptop. (curl http://siacoin.com:29989)

**Comment by DavidVorick** [comment]
when running `git reset --hard origin/master` Adam was getting an error about 'ambiguous something something'.

not sure what was going on. Fixed it by `git reset --hard HEAD~3 && git pull origin master`

Ultimately, probably best that we never push force to master or --amend master.
